### ISSUE TITLE
how to recognize the original input guide sequences from crispritz search results

### ISSUE THREAD

**Issue by Huanle** [pinellolab/CRISPRitz#7]
Hi There,

Thanks for making this valuable and innovative program available. 
I am interested in incorporating it into my current pipeline. 
However, I wonder if it is possible to add one more column into the results from the `search` module to indicate the original guide sequence?

Thanks a lot.

Best Regards,
Huanle

**Comment by samuelecancellieri** [comment]
Hi @Huanle 
the feature is not available in CRISPRitz, but it's easy to extract the original guide, from the aligned one, since you just need to remove the '-' marks and then add a column in the file.
If you what to try a more complete software, with more features and a GUI, we are also developing CRISPRme (http://crisprme.di.univr.it/)
