### ISSUE TITLE
how to understand the radar chart?

### ISSUE THREAD

**Issue by Huanle** [pinellolab/CRISPRitz#8]
Hi @lucapinello ,

thank you and your colleagues for developing crispritz.
I have a question regarding the output radar chart of crispritz. 
I can not understand the radar chart? 
In the example image, what is the `MAX VALUE`?
What are the numbers in the parentheses? Are they the number of guides or features?
What are those decimal numbers? Are they proportions accounting for the total number of guides in the same category (defined using the number of mismatches) or the area size of the inner circles?

Thanks a lot and I look forward to your help.

![image](https://user-images.githubusercontent.com/909201/180908773-060c29c4-ac38-4195-8e81-9be624681bb9.png)

**Comment by samuelecancellieri** [comment]
Hi @Huanle,
first, thanks for using the software.
I've seen all the other issues, I will reply asap (sorry I got no mail from this repo).

The radar chart is sharing two information about your search,
the number in brackets, e.g., CTCF (16), counts the number of targets resulting from your search with the specified number of mismatches (bulges are automatically taken, so if you select 4mm you select all the targets with 4mm and any count of bulges) that falls into CTCF category (a target can fall into more than one annotation category, hence the sum count of all categories can be higher than the number of reported target).

The value in each y-axis (from 0 to 1) is the percentile occupied by results you are plotting.
Trying to explain clearer, if you run a search with more than one guide, for each category you will have a distribution of values, for example, guide1 has 117 CTCF targets with 4mm, guide2 has 103 CTCF targets with 4mm, guide3 has 56 CTCF target with 4mm and so on, if you plot guideN that has 99 CTCF targets with 4mm, guideN will be in a percentile lower than guide1 and guide2 but higher than guide3.
Connecting the point of this percentile representation, you will obtain an area in the plot. 
Bigger the area, "worst" the guide (worst is in marks due to the complex meaning of worst when talking about CRISPR results).
The upper left table, report the higher value in each category for the specific count of mismatches.

Hope the explanation is clear.
If you have any other question, you can email me, samuele.cancellieri@univr.it

Thanks again for using the software.
Best,
Samuele

**Comment by Huanle** [comment]
thanks a lot @samuelecancellieri 
this clarifies my confusion.

Best
